### ISSUE TITLE
dd_1d_shared code question

### ISSUE THREAD

**Issue by yoshi95** [myurtoglu/cudaforengineers#1]
@myurtoglu

hi, wondering why the following works
in this line (https://github.com/myurtoglu/cudaforengineers/blob/master/dd_1d_shared/kernel.cu#L18)
`s_in[s_idx - RAD] = d_in[i - RAD];`
for the 1st thread `threadIdx.x = i = 0`, `i-RAD = -1` and should run into errors for `d_in[i-RAD]` right?

**Comment by myurtoglu** [comment]
Hi @yoshi95, except the first block, the first thread reads still some meaningful and important value since `threadIdx.x = 0` does not necessarily mean `i = 0`. However, for the first block, first thread case, it is indeed `-1`. Since there is no bounds checking in C/C++, `d_in[-1]` results in reading of some garbage value. This is not a big deal, since that only affects `result_parallel[0]`, and `result_parallel[0]` is not taken into account [here](https://github.com/myurtoglu/cudaforengineers/blob/master/dd_1d_shared/main.cpp#L22-L25). The reasoning behind this is; there should be some boundary condition actually prescribed (i.e. Dirichlet Boundary conditions) and we haven't specified it, so we don't worry about it.
