### ISSUE TITLE
dist_v2_cuda/kernel.cu: why ref is not copied to device?

### ISSUE THREAD

**Issue by yuanshuoastro** [myurtoglu/cudaforengineers#4]
Dear Authors,
I wonder in [https://github.com/myurtoglu/cudaforengineers/blob/master/dist_v2_cuda/kernel.cu](url):

```

// Copy input data from host to device
  cudaMemcpy(d_in, in, len*sizeof(float), cudaMemcpyHostToDevice);
  
  // Launch kernel to compute and store distance values
  distanceKernel<<<len/TPB, TPB>>>(d_out, d_in, ref);

 ```

When the kernal is called, why **ref** is not send to device by cudaMemcpy? 

Thanks!

**Comment by myurtoglu** [comment]
Maybe this Q & A can be helpful to clarify this: https://stackoverflow.com/a/8303535/2458319

In essence, when we pass d_out, d_in, and ref, they are all "values" on the host side. The difference is: d_out and d_in are references to float arrays in the device memory, and ref is just a primitive (int). With some limitations (http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#function-parameters), you can directly pass primitive values to kernels without needing cudaMemcpy operations.

Also, note that, if you need a primitive result from the kernel, things will be different. Trying to write the result back to the ref is not going to work since its passed by value, and since kernels always have a void return type you won't be able to return anything with "return". Thus, you will still have to pass the primitive by reference unlike the ref here. d_centroidCol, d_centroidRow, d_pixelCount are good examples of this in https://github.com/myurtoglu/cudaforengineers/blob/master/centroid_2d/kernel.cu.

**Comment by yuanshuoastro** [comment]
Thanks!
