### ISSUE TITLE
A tiny issue in the souce code in section 5.2.1

### ISSUE THREAD

**Issue by lelleMU** [myurtoglu/cudaforengineers#5]
`void ddkernel(float *d_out, const float *d_in, int size, float h){`
`       const int i = threadIdx.x + blockDim.x*blockIdx.x;`
`       if (i >= size) return;`
`       d_out[i] = (d_in[i-1]+d_in[i+1]-2.f*d_in[i])/(h*h);`
`}`
With this part, I can not get the right result.
I made a tiny change in the code,like this:

`if (i >= size - 1 || i == 0) return;`
	
Then I get the right result.
Hope you can improve it.

**Comment by myurtoglu** [comment]
[Similar discussion here](http://disq.us/p/19h8xhr). Your recommendation is indeed a good way to fix this issue. Originally out of bounds access didn't cause any problems when we tested the code in our systems [and we didn't worry about `d_out[0]` and `d_out[size - 1]` result values anyway](https://github.com/myurtoglu/cudaforengineers/blob/e810ee398c90b6bf543e860f8963760910aa6348/dd_1d_shared/main.cpp#L22). Thus we kept the code like this. However, we later received reports of crashes in some systems. In that case, using `if (i >= size - 1 || i == 0) return;` instead of `if (i >= size) return;` will indeed fix the problem.

Thanks!

**Comment by myurtoglu** [comment]
[Updated the repo now.](https://github.com/myurtoglu/cudaforengineers/commit/b9d90c795dfa63988985e8caee9a1d2a00fb98b0) Thanks!
